# Error com√∫n al usar los scopes
## D√≠a 6

Un error com√∫n entre los programadores de Python, especialmente los principiantes, es el "error de la variable ```global``` y ```local``` con el mismo nombre". Esto ocurre cuando una variable ```global``` y una variable ```local``` dentro de una funci√≥n tienen el mismo nombre, lo que puede llevar a comportamientos confusos y errores dif√≠ciles de rastrear.

**Python trata las variables definidas dentro de una funci√≥n como locales**, a menos que se especifique expl√≠citamente lo contrario. Si una variable dentro de una funci√≥n tiene el mismo nombre que una variable ```global```, la variable ```local``` ocultar√° a la global dentro del √°mbito de la funci√≥n. Esto puede causar errores si la funci√≥n intenta modificar la variable global sin declararla como tal.

**[‚û°Ô∏è AQU√ç PUEDES VER EL C√ìDIGO FUNCIONANDO ‚¨ÖÔ∏è](/notebooks/dia6-modificacion_listas.ipynb)** 

```Python

# Lista original con algunos n√∫meros
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# M√âTODO INCORRECTO: Modificar la lista mientras se itera
for numero in numeros:
    if numero % 2 != 0:
        numeros.remove(numero)

# Lista despu√©s de intentar eliminar n√∫meros impares (M√âTODO INCORRECTO)
resultado_incorrecto = numeros

# Restablecemos la lista a su estado original
numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9]

# M√âTODO CORRECTO: Iterar sobre una copia de la lista
for numero in numeros[:]:  # Usando [:] podemos crear una copia para ser usada con el for
    if numero % 2 != 0:
        numeros.remove(numero)

# Lista despu√©s de eliminar n√∫meros impares (M√âTODO CORRECTO)
resultado_correcto = numeros

print(resultado_incorrecto, resultado_correcto)

```

### M√©todo Incorrecto (Sin usar global):

- En la funci√≥n ```incrementar_incorrecto()```, intentamos incrementar la variable global contador sin declararla como global
- Esto resulta en un error: ```local variable 'contador' referenced before assignment```. Este error ocurre porque Python asume que contador en la funci√≥n es una variable local, dado que estamos intentando asignarle un valor. Como a√∫n no est√° asignada en el √°mbito local, se produce un error.


### M√©todo Correcto (Usando global):

- En la funci√≥n ```incrementar_correcto()```, declaramos contador como una variable global antes de modificarla.
  
- Al hacer esto, le decimos a Python que use la variable global contador en lugar de crear una nueva variable local con el mismo nombre.
- La funci√≥n incrementa correctamente el valor de la variable global contador, y el ```resultado_correcto``` es 1.


**De hecho hay un TikTok que lo explica**
[‚û°Ô∏èDALE CLIC AQU√ç PARA VERLO‚¨ÖÔ∏è]()

| [‚¨ÖÔ∏è D√≠a 5 ](/dias/dia5-enumerate.md) | Con üíñ por [@brujeriatech](https://www.instagram.com/brujeriatech/) | [D√≠a 7 ‚û°Ô∏è]()|
|:------------- |:---------------:| -------------:|

